import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				<nav className="flex gap-6 px-16 py-6">
					<Link href="/">Home</Link>
					<Link href="/projects">Projects</Link>
				</nav>
				{children}
			</body>
		</html>
	);
}
